---
- name: Add nginx apt key
  apt_key:
    url='http://nginx.org/keys/nginx_signing.key'

- name: Add nginx apt repo
  apt_repository:
    repo="deb http://nginx.org/packages/{{ ansible_lsb.id|lower }}/ {{ ansible_lsb.codename }} nginx"
    update_cache=yes

- name: Install Nginx apt package
  apt: pkg=nginx state=present

- name: Install python-passlib
  apt: pkg=python-passlib state=present
- name: Disable default servers
  file:
    path=/etc/nginx/conf.d/{{ item.path }}
    state=absent
  with_items:
    - { path: 'default.conf' }
    - { path: 'example_ssl.conf' }

- name: Password protect elastic cluster
  htpasswd: path=/etc/nginx/conf.d/es_passwd name={{ item.key }} password={{ item.value.password }}  owner=nginx group=nginx mode=0640
  with_dict: "{{ users }}"
  tags:
    - nginx_conf

- name: Upload nginx config
  template: src={{ item }} dest=/etc/nginx/conf.d/{{item}}.conf
  with_items:
    - es-lb
    - kibana-default
  notify: Restart nginx
  tags:
    - nginx_conf
