# file: nginx/tasks/main.yml

- include: package.yml
- include: scripts.yml
- include: configure.yml
- include: default_site.yml
- include: sites.yml
- include: monit.yml
  when: monit_protection is defined and monit_protection == true
